# Environment for working with nisar validation tools
name: nisarcryo
#
channels:
  - conda-forge
dependencies:
  - python=3.12
  - geopandas
  - rioxarray
  - lxml
  - gdal
  - blosc
  - curl
  - dask
  - datashader
  - fsspec
  - gdal
  - geoviews  
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
 # - panel<1
  - param
  - pip
  - progressbar2
  - qgis
  - rasterio
  #- stackstac
  - tiledb
 
  